  using Autodesk.AutoCAD.ApplicationServices;
using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.Geometry;
using Autodesk.AutoCAD.Runtime;

public class LineDrawer
{
    [CommandMethod("DrawMyLine")]
    public void DrawLine()
    {
        // Get the current document and database
        Document doc = Application.DocumentManager.MdiActiveDocument;
        Database db = doc.Database;

        // Start a transaction
        using (Transaction trans = db.TransactionManager.StartTransaction())
        {
            // Open the Block table for read
            BlockTable blockTable = trans.GetObject(db.BlockTableId, OpenMode.ForRead) as BlockTable;

            // Open the Block table record Model space for write
            BlockTableRecord blockTableRecord = trans.GetObject(blockTable[BlockTableRecord.ModelSpace], OpenMode.ForWrite) as BlockTableRecord;

            // Create a line from point (0,0,0) to (100,100,0)
            Line line = new Line(new Point3d(0, 0, 0), new Point3d(100, 100, 0));

            // Add the new object to the block table record and the transaction
            blockTableRecord.AppendEntity(line);
            trans.AddNewlyCreatedDBObject(line, true);

            // Commit the changes and dispose of the transaction
            trans.Commit();
        }
    }
}
